#cloud-config
#
# @sacloud-name "Switching Consoles for RancherOS"
# @sacloud-require-archive distro-rancheros
# @sacloud-desc-begin
# RancherOSのコンソールを切り替えます。詳細は下記URLをご確認ください。
# https://docs.rancher.com/os/configuration/switching-consoles/
# @sacloud-desc-end
#
# @sacloud-select-begin required default=default console "コンソール"
# default
# alpine
# centos
# debian
# fedora
# ubuntu
# @sacloud-select-end

rancher:
  console: @@@console@@@